const STATES = {
    'Alabama': 'al',
    'Alaska': 'ak',
    'Arizona': 'az',
    'Arkansas': 'ar',
    'California': 'ca',
    'Colorado': 'co',
    'Connecticut': 'ct',
    'Florida': 'fl',
    'Georgia': 'ga',
    'Hawaii': 'hi',
    'Idaho': 'id',
    'Illinois': 'il',
    'Indiana': 'in',
    'Iowa': 'ia',
    'Kansas': 'ks',
    'Kentucky': 'ky',
    'Louisiana': 'la',
    'Maine': 'me',
    'Maryland': 'md',
    'Massachusetts': 'ma',
    'Michigan': 'mi',
    'Minnesota': 'mn',
    'Mississippi': 'ms',
    'Missouri': 'mo',
    'Montana': 'mt',
    'Nebraska': 'ne',
    'Nevada': 'nv',
    'New Hampshire': 'nh',
    'New Jersey': 'nj',
    'New Mexico': 'nm',
    'New York': 'ny',
    'North Carolina': 'nc',
    'North Dakota': 'nd',
    'Ohio': 'oh',
    'Oklahoma': 'ok',
    'Oregon': 'or',
    'Pennsylvania': 'pa',
    // 'Puerto Rico',
    'Rhode Island': 'ri',
    'South Carolina': 'sc',
    'South Dakota': 'sd',
    'Tennessee': 'tn',
    'Texas': 'tx',
    // 'U.S. Pacific Trust Territories and Possessions',
    // 'U.S. Virgin Islands',
    'Utah': 'ut',
    'Vermont': 'vt',
    'Virginia': 'va',
    'Washington': 'wa',
    'West Virginia': 'wv',
    'Wisconsin': 'wi',
    'Wyoming': 'wy'
}

const AIRLINES = [
    'Air Wisconsin Airlines Corp',
    'Alaska Airlines Inc.',
    'Allegiant Air',
    'American Airlines Inc.',
    'CommuteAir LLC dba CommuteAir',
    'Delta Air Lines Inc.',
    'Endeavor Air Inc.',
    'Envoy Air',
    'Frontier Airlines Inc.',
    'GoJet Airlines LLC d/b/a United Express',
    'Hawaiian Airlines Inc.',
    'Horizon Air',
    'JetBlue Airways',
    'Mesa Airlines Inc.',
    'PSA Airlines Inc.'
]

const CORRECTION_MAP = {
    'LA': { 'x': -20, 'y': 0 },
    'MA': { 'x': 10, 'y': -4 },
    'RI': { 'x': 0, 'y': 1 },
    'VA': { 'x': 20, 'y': 0},
    'MD': { 'x': 15, 'y': -4},
    'FL': { 'x': 45, 'y': 0},
    'ID': { 'x': -10, 'y': 0},
    'NJ': { 'x': 5, 'y': 0},
    'DE': { 'x': 2, 'y': 8},
    'MN': { 'x': -20, 'y': 0},
    'KY': { 'x': 0, 'y': 10},
    'MI': { 'x': 25, 'y': 30},
    'TX': { 'x': 25, 'y': 0},
    'WV': { 'x': -10, 'y': 5},
    'NH': { 'x': -3, 'y': 10},
    'CA': { 'x': -15, 'y': 0},
}

const DELAY_DATA_MAPPING = {
    "carrier": 5,
    "weather": 6,
    "nas": 7,
    "security": 8,
    "late_aircraft": 9
}

const SCALE_MAP = {
    'tx': 2.5,
    'ca': 2.5,
    'nv': 3.5,
    'mn': 4.5,
    'fl': 4.5,
    'az': 4.5,
    'mi': 4.5,
    'tn': 6,
    'ar': 7,
    'sd': 7,
    'mo': 6,
    'wa': 7,
    'ak': 4,
    'wv': 7,
    'sc': 7,
    'oh': 7,
    'ky': 7,
    'ia': 8,
    'nh': 8,
    'ny': 6,
    'vt': 8,
    'ma': 9,
    'ct': 9,
    'nd': 8,
    'ne': 9,
    'id': 3.5,
}

const RESET_COORDINATE_MAP = new Map()

const AIRPORTS = [
    'Aberdeen, SD: Aberdeen Regional',
    'Abilene, TX: Abilene Regional',
    'Adak Island, AK: Adak',
    'Aguadilla, PR: Rafael Hernandez',
    'Akron, OH: Akron-Canton Regional',
    'Albany, GA: Southwest Georgia Regional',
    'Albany, NY: Albany International',
    'Albuquerque, NM: Albuquerque International Sunport',
    'Alexandria, LA: Alexandria International',
    'Allentown/Bethlehem/Easton, PA: Lehigh Valley International',
    'Alpena, MI: Alpena County Regional',
    'Amarillo, TX: Rick Husband Amarillo International',
    'Anchorage, AK: Ted Stevens Anchorage International',
    'Appleton, WI: Appleton International',
    'Arcata/Eureka, CA: California Redwood Coast Humboldt County',
    'Asheville, NC: Asheville Regional',
    'Ashland, WV: Tri-State/Milton J. Ferguson Field',
    'Aspen, CO: Aspen Pitkin County Sardy Field',
    'Atlanta, GA: Hartsfield-Jackson Atlanta International',
    'Atlantic City, NJ: Atlantic City International',
    'Augusta, GA: Augusta Regional at Bush Field',
    'Austin, TX: Austin - Bergstrom International',
    'Bakersfield, CA: Meadows Field',
    'Baltimore, MD: Baltimore/Washington International Thurgood Marshall',
    'Bangor, ME: Bangor International',
    'Barrow, AK: Wiley Post/Will Rogers Memorial',
    'Baton Rouge, LA: Baton Rouge Metropolitan/Ryan Field',
    'Beaumont/Port Arthur, TX: Jack Brooks Regional',
    'Belleville, IL: Scott AFB MidAmerica St Louis',
    'Bellingham, WA: Bellingham International',
    'Bemidji, MN: Bemidji Regional',
    'Bend/Redmond, OR: Roberts Field',
    'Bethel, AK: Bethel Airport',
    'Billings, MT: Billings Logan International',
    'Binghamton, NY: Greater Binghamton/Edwin A. Link Field',
    'Birmingham, AL: Birmingham-Shuttlesworth International',
    'Bishop, CA: Bishop Airport',
    'Bismarck/Mandan, ND: Bismarck Municipal',
    'Bloomington/Normal, IL: Central Il Regional Airport at Bloomington',
    'Boise, ID: Boise Air Terminal',
    'Boston, MA: Logan International',
    'Bozeman, MT: Bozeman Yellowstone International',
    'Brainerd, MN: Brainerd Lakes Regional',
    'Bristol/Johnson City/Kingsport, TN: Tri Cities',
    'Brownsville, TX: Brownsville South Padre Island International',
    'Brunswick, GA: Brunswick Golden Isles',
    'Buffalo, NY: Buffalo Niagara International',
    'Burbank, CA: Bob Hope',
    'Burlington, VT: Burlington International',
    'Butte, MT: Bert Mooney',
    'Casper, WY: Casper/Natrona County International',
    'Cedar City, UT: Cedar City Regional',
    'Cedar Rapids/Iowa City, IA: The Eastern Iowa',
    'Champaign/Urbana, IL: University of Illinois/Willard',
    'Charleston, SC: Charleston AFB/International',
    'Charleston/Dunbar, WV: West Virginia International Yeager',
    'Charlotte Amalie, VI: Cyril E King',
    'Charlotte, NC: Charlotte Douglas International',
    'Charlottesville, VA: Charlottesville Albemarle',
    'Chattanooga, TN: Lovell Field',
    'Cheyenne, WY: Cheyenne Regional/Jerry Olson Field',
    'Chicago, IL: Chicago Midway International',
    "Chicago, IL: Chicago O'Hare International",
    'Christiansted, VI: Henry E. Rohlsen',
    'Cincinnati, OH: Cincinnati/Northern Kentucky International',
    'Clarksburg/Fairmont, WV: North Central West Virginia',
    'Cleveland, OH: Cleveland-Hopkins International',
    'Cody, WY: Yellowstone Regional',
    'College Station/Bryan, TX: Easterwood Field',
    'Colorado Springs, CO: City of Colorado Springs Municipal',
    'Columbia, MO: Columbia Regional',
    'Columbia, SC: Columbia Metropolitan',
    'Columbus, GA: Columbus Airport',
    'Columbus, MS: Golden Triangle Regional',
    'Columbus, OH: John Glenn Columbus International',
    'Columbus, OH: Rickenbacker International',
    'Concord, NC: Concord Padgett Regional',
    'Cordova, AK: Merle K Mudhole Smith',
    'Corpus Christi, TX: Corpus Christi International',
    'Dallas, TX: Dallas Love Field',
    'Dallas/Fort Worth, TX: Dallas/Fort Worth International',
    'Dayton, OH: James M Cox/Dayton International',
    'Daytona Beach, FL: Daytona Beach International',
    'Deadhorse, AK: Deadhorse Airport',
    'Decatur, IL: Decatur Airport',
    'Denver, CO: Denver International',
    'Des Moines, IA: Des Moines International',
    'Detroit, MI: Detroit Metro Wayne County',
    'Devils Lake, ND: Devils Lake Regional',
    'Dickinson, ND: Dickinson - Theodore Roosevelt Regional',
    'Dillingham, AK: Dillingham Airport',
    'Dodge City, KS: Dodge City Regional',
    'Dothan, AL: Dothan Regional',
    'Duluth, MN: Duluth International',
    'Durango, CO: Durango La Plata County',
    'Eagle, CO: Eagle County Regional',
    'El Paso, TX: El Paso International',
    'Elko, NV: Elko Regional',
    'Elmira/Corning, NY: Elmira/Corning Regional',
    'Erie, PA: Erie International/Tom Ridge Field',
    'Escanaba, MI: Delta County',
    'Eugene, OR: Mahlon Sweet Field',
    'Evansville, IN: Evansville Regional',
    'Everett, WA: Snohomish County',
    'Fairbanks, AK: Fairbanks International',
    'Fargo, ND: Hector International',
    'Fayetteville, AR: Northwest Arkansas National',
    'Fayetteville, NC: Fayetteville Regional/Grannis Field',
    'Flagstaff, AZ: Flagstaff Pulliam',
    'Flint, MI: Bishop International',
    'Florence, SC: Florence Regional',
    'Fort Dodge, IA: Fort Dodge Regional',
    'Fort Lauderdale, FL: Fort Lauderdale-Hollywood International',
    'Fort Myers, FL: Southwest Florida International',
    'Fort Smith, AR: Fort Smith Regional',
    'Fort Wayne, IN: Fort Wayne International',
    'Fresno, CA: Fresno Yosemite International',
    'Gainesville, FL: Gainesville Regional',
    'Garden City, KS: Garden City Regional',
    'Gillette, WY: Northeast Wyoming Regional',
    'Grand Forks, ND: Grand Forks International',
    'Grand Island, NE: Central Nebraska Regional',
    'Grand Junction, CO: Grand Junction Regional',
    'Grand Rapids, MI: Gerald R. Ford International',
    'Great Falls, MT: Great Falls International',
    'Green Bay, WI: Green Bay Austin Straubel International',
    'Greensboro/High Point, NC: Piedmont Triad International',
    'Greenville, NC: Pitt Greenville',
    'Greer, SC: Greenville-Spartanburg International',
    'Guam, TT: Guam International',
    'Gulfport/Biloxi, MS: Gulfport-Biloxi International',
    'Gunnison, CO: Gunnison-Crested Butte Regional',
    'Gustavus, AK: Gustavus Airport',
    'Hagerstown, MD: Hagerstown Regional-Richard A. Henson Field',
    'Hancock/Houghton, MI: Houghton County Memorial',
    'Harlingen/San Benito, TX: Valley International',
    'Harrisburg, PA: Harrisburg International',
    'Hartford, CT: Bradley International',
    'Hattiesburg/Laurel, MS: Hattiesburg-Laurel Regional',
    'Hayden, CO: Yampa Valley',
    'Hays, KS: Hays Regional',
    'Helena, MT: Helena Regional',
    'Hibbing, MN: Range Regional',
    'Hilo, HI: Hilo International',
    'Hilton Head, SC: Hilton Head Airport',
    'Hobbs, NM: Lea County Regional',
    'Honolulu, HI: Daniel K Inouye International',
    'Houston, TX: George Bush Intercontinental/Houston',
    'Houston, TX: William P Hobby',
    'Huntsville, AL: Huntsville International-Carl T Jones Field',
    'Hyannis, MA: Cape Cod Gateway',
    'Idaho Falls, ID: Idaho Falls Regional',
    'Indianapolis, IN: Indianapolis International',
    'International Falls, MN: Falls International Einarson Field',
    'Iron Mountain/Kingsfd, MI: Ford',
    'Islip, NY: Long Island MacArthur',
    'Ithaca/Cortland, NY: Ithaca Tompkins International',
    'Jackson, WY: Jackson Hole',
    'Jackson/Vicksburg, MS: Jackson Medgar Wiley Evers International',
    'Jacksonville, FL: Jacksonville International',
    'Jacksonville/Camp Lejeune, NC: Albert J Ellis',
    'Jamestown, ND: Jamestown Regional',
    'Johnstown, PA: John Murtha Johnstown-Cambria County',
    'Joplin, MO: Joplin Regional',
    'Juneau, AK: Juneau International',
    'Kahului, HI: Kahului Airport',
    'Kalamazoo, MI: Kalamazoo/Battle Creek International',
    'Kalispell, MT: Glacier Park International',
    'Kansas City, MO: Kansas City International',
    'Kearney, NE: Kearney Regional',
    'Ketchikan, AK: Ketchikan International',
    'Key West, FL: Key West International',
    'Killeen, TX: Robert Gray AAF',
    'King Salmon, AK: King Salmon Airport',
    'Knoxville, TN: McGhee Tyson',
    'Kodiak, AK: Kodiak Airport',
    'Kona, HI: Ellison Onizuka Kona International at Keahole',
    'Kotzebue, AK: Ralph Wien Memorial',
    'La Crosse, WI: La Crosse Regional',
    'Lafayette, LA: Lafayette Regional Paul Fournet Field',
    'Lake Charles, LA: Lake Charles Regional',
    'Lansing, MI: Capital Region International',
    'Laramie, WY: Laramie Regional',
    'Laredo, TX: Laredo International',
    'Las Vegas, NV: Harry Reid International',
    'Latrobe, PA: Arnold Palmer Regional',
    'Lawton/Fort Sill, OK: Lawton-Fort Sill Regional',
    'Lewiston, ID: Lewiston Nez Perce County',
    'Lexington, KY: Blue Grass',
    'Liberal, KS: Liberal Mid-America Regional',
    'Lihue, HI: Lihue Airport',
    'Lincoln, NE: Lincoln Airport',
    'Little Rock, AR: Bill and Hillary Clinton Nat Adams Field',
    'Long Beach, CA: Long Beach Airport',
    'Longview, TX: East Texas Regional',
    'Los Angeles, CA: Los Angeles International',
    'Louisville, KY: Louisville Muhammad Ali International',
    'Lubbock, TX: Lubbock Preston Smith International',
    'Lynchburg, VA: Lynchburg Regional/Preston Glenn Field',
    'Madison, WI: Dane County Regional-Truax Field',
    'Manchester, NH: Manchester Boston Regional',
    'Manhattan/Ft. Riley, KS: Manhattan Regional',
    'Marquette, MI: Marquette Sawyer Regional',
    "Martha's Vineyard, MA: Martha's Vineyard Airport",
    'Mason City, IA: Mason City Municipal',
    'Medford, OR: Rogue Valley International - Medford',
    'Melbourne, FL: Melbourne Orlando International',
    'Memphis, TN: Memphis International',
    'Meridian, MS: Key Field',
    'Miami, FL: Miami International',
    'Midland/Odessa, TX: Midland International Air and Space Port',
    'Milwaukee, WI: General Mitchell International',
    'Minneapolis, MN: Minneapolis-St Paul International',
    'Minot, ND: Minot International',
    'Mission/McAllen/Edinburg, TX: McAllen International',
    'Missoula, MT: Missoula Montana',
    'Moab, UT: Canyonlands Regional',
    'Mobile, AL: Mobile Regional',
    'Moline, IL: Quad Cities International',
    'Monroe, LA: Monroe Regional',
    'Monterey, CA: Monterey Regional',
    'Montgomery, AL: Montgomery Regional',
    'Montrose/Delta, CO: Montrose Regional',
    'Mosinee, WI: Central Wisconsin',
    'Myrtle Beach, SC: Myrtle Beach International',
    'Nantucket, MA: Nantucket Memorial',
    'Nashville, TN: Nashville International',
    'New Bern/Morehead/Beaufort, NC: Coastal Carolina Regional',
    'New Orleans, LA: Louis Armstrong New Orleans International',
    'New York, NY: John F. Kennedy International',
    'New York, NY: LaGuardia',
    'Newark, NJ: Newark Liberty International',
    'Newburgh/Poughkeepsie, NY: New York Stewart International',
    'Newport News/Williamsburg, VA: Newport News/Williamsburg International',
    'Niagara Falls, NY: Niagara Falls International',
    'Nome, AK: Nome Airport',
    'Norfolk, VA: Norfolk International',
    'North Bend/Coos Bay, OR: Southwest Oregon Regional',
    'North Platte, NE: North Platte Regional Airport Lee Bird Field',
    'Oakland, CA: Metro Oakland International',
    'Oklahoma City, OK: Will Rogers World',
    'Omaha, NE: Eppley Airfield',
    'Ontario, CA: Ontario International',
    'Orlando, FL: Orlando International',
    'Pago Pago, TT: Pago Pago International',
    'Palm Springs, CA: Palm Springs International',
    'Panama City, FL: Northwest Florida Beaches International',
    'Pasco/Kennewick/Richland, WA: Tri Cities',
    'Pellston, MI: Pellston Regional Airport of Emmet County',
    'Pensacola, FL: Pensacola International',
    'Peoria, IL: General Downing - Peoria International',
    'Petersburg, AK: Petersburg James A Johnson',
    'Philadelphia, PA: Philadelphia International',
    'Phoenix, AZ: Phoenix - Mesa Gateway',
    'Phoenix, AZ: Phoenix Sky Harbor International',
    'Pittsburgh, PA: Pittsburgh International',
    'Plattsburgh, NY: Plattsburgh International',
    'Pocatello, ID: Pocatello Regional',
    'Ponce, PR: Mercedita',
    'Portland, ME: Portland International Jetport',
    'Portland, OR: Portland International',
    'Portsmouth, NH: Portsmouth International at Pease',
    'Prescott, AZ: Prescott Regional Ernest A Love Field',
    'Presque Isle/Houlton, ME: Presque Isle International',
    'Providence, RI: Rhode Island Tf Green International',
    'Provo, UT: Provo Municipal',
    'Pullman, WA: Pullman Moscow Regional',
    'Punta Gorda, FL: Punta Gorda Airport',
    'Raleigh/Durham, NC: Raleigh-Durham International',
    'Rapid City, SD: Rapid City Regional',
    'Redding, CA: Redding Regional',
    'Reno, NV: Reno/Tahoe International',
    'Rhinelander, WI: Rhinelander/Oneida County',
    'Richmond, VA: Richmond International',
    'Riverton/Lander, WY: Central Wyoming Regional',
    'Roanoke, VA: Roanoke Blacksburg Regional',
    'Rochester, MN: Rochester International',
    'Rochester, NY: Frederick Douglass Grtr Rochester International',
    'Rock Springs, WY: Southwest Wyoming Regional',
    'Rockford, IL: Chicago/Rockford International',
    'Roswell, NM: Roswell Air Center',
    'Sacramento, CA: Sacramento International',
    'Saginaw/Bay City/Midland, MI: MBS International',
    'Saipan, TT: Francisco C. Ada Saipan International',
    'Salina, KS: Salina Regional',
    'Salisbury, MD: Salisbury-Ocean City/Wicomico Regional',
    'Salt Lake City, UT: Salt Lake City International',
    'San Angelo, TX: San Angelo Regional/Mathis Field',
    'San Antonio, TX: San Antonio International',
    'San Diego, CA: San Diego International',
    'San Francisco, CA: San Francisco International',
    'San Jose, CA: Norman Y. Mineta San Jose International',
    'San Juan, PR: Luis Munoz Marin International',
    'San Luis Obispo, CA: San Luis County Regional',
    'Sanford, FL: Orlando Sanford International',
    'Santa Ana, CA: John Wayne Airport-Orange County',
    'Santa Barbara, CA: Santa Barbara Municipal',
    'Santa Fe, NM: Santa Fe Municipal',
    'Santa Maria, CA: Santa Maria Public/Capt. G. Allan Hancock Field',
    'Santa Rosa, CA: Charles M. Schulz - Sonoma County',
    'Sarasota/Bradenton, FL: Sarasota/Bradenton International',
    'Sault Ste. Marie, MI: Chippewa County International',
    'Savannah, GA: Savannah/Hilton Head International',
    'Scottsbluff, NE: Western Neb. Regional/William B. Heilig Field',
    'Scranton/Wilkes-Barre, PA: Wilkes Barre Scranton International',
    'Seattle, WA: Seattle/Tacoma International',
    'Sheridan, WY: Sheridan County',
    'Shreveport, LA: Shreveport Regional',
    'Sioux City, IA: Sioux Gateway Brig Gen Bud Day Field',
    'Sioux Falls, SD: Joe Foss Field',
    'Sitka, AK: Sitka Rocky Gutierrez',
    'South Bend, IN: South Bend International',
    'Spokane, WA: Spokane International',
    'Springfield, IL: Abraham Lincoln Capital',
    'Springfield, MO: Springfield-Branson National',
    'St. Cloud, MN: St. Cloud Regional',
    'St. George, UT: St George Regional',
    'St. Louis, MO: St Louis Lambert International',
    'St. Petersburg, FL: St Pete Clearwater International',
    'State College, PA: University Park',
    'Stillwater, OK: Stillwater Regional',
    'Stockton, CA: Stockton Metro',
    'Sun Valley/Hailey/Ketchum, ID: Friedman Memorial',
    'Syracuse, NY: Syracuse Hancock International',
    'Tallahassee, FL: Tallahassee International',
    'Tampa, FL: Tampa International',
    'Texarkana, AR: Texarkana Regional-Webb Field',
    'Toledo, OH: Eugene F Kranz Toledo Express',
    'Traverse City, MI: Cherry Capital',
    'Trenton, NJ: Trenton Mercer',
    'Tucson, AZ: Tucson International',
    'Tulsa, OK: Tulsa International',
    'Twin Falls, ID: Joslin Field - Magic Valley Regional',
    'Tyler, TX: Tyler Pounds Regional',
    'Valdosta, GA: Valdosta Regional',
    'Valparaiso, FL: Eglin AFB Destin Fort Walton Beach',
    'Vernal, UT: Vernal Regional',
    'Victoria, TX: Victoria Regional',
    'Waco, TX: Waco Regional',
    'Walla Walla, WA: Walla Walla Regional',
    'Washington, DC: Ronald Reagan Washington National',
    'Washington, DC: Washington Dulles International',
    'Waterloo, IA: Waterloo Regional',
    'Watertown, NY: Watertown International',
    'Wenatchee, WA: Pangborn Memorial',
    'West Palm Beach/Palm Beach, FL: Palm Beach International',
    'West Yellowstone, MT: Yellowstone',
    'White Plains, NY: Westchester County',
    'Wichita Falls, TX: Sheppard AFB/Wichita Falls Municipal',
    'Wichita, KS: Wichita Dwight D Eisenhower National',
    'Williston, ND: Williston Basin International',
    'Wilmington, NC: Wilmington International',
    'Worcester, MA: Worcester Regional',
    'Wrangell, AK: Wrangell Airport',
    'Yakima, WA: Yakima Air Terminal/McAllister Field',
    'Yakutat, AK: Yakutat Airport',
    'Yuma, AZ: Yuma MCAS/Yuma International'
]

const CACHE = new Map()